name: Generate Snake Animation

on:
  schedule:
    # Executa 1 vez por dia (às 00h UTC)
    - cron: "0 0 * * *"
  workflow_dispatch: # permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Pega o código do repositório
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # importante pra pegar o histórico do git

      # Gera a cobrinha
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: alclides
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      # Publica na branch "output"
      - name: Push Snake to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
